/* GitHub Pages invitation. RSVP remains in the existing shared database.
   A user-opened first-party window performs registration; no tokens or server
   credentials are exposed and no cross-origin security settings are changed. */
(()=>{'use strict';
const BACKEND='https://hovden-hyttelan-2026.higgsfield.app';
const $=id=>document.getElementById(id);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaultDeadline=Date.parse('2026-09-25T18:00:00+02:00');
let state=null,filter='all',popup=null,nonce='',clockBase=Date.now(),perfBase=performance.now(),lastExpired=false,toastTimer=null;
const now=()=>clockBase+(performance.now()-perfBase);
const formatDeadline=n=>new Intl.DateTimeFormat('nb-NO',{timeZone:'Europe/Oslo',weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'}).format(new Date(n));
const formatDate=s=>new Intl.DateTimeFormat('nb-NO',{timeZone:'Europe/Oslo',day:'numeric',month:'long',year:'numeric'}).format(new Date(s+'T12:00:00Z'));
function toast(s){clearTimeout(toastTimer);$('toast').textContent=s;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,6500);}
function imageURL(s){if(typeof s!=='string')return '';if(/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(s)&&s.length<350000)return s;try{const u=new URL(s);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}}
function validState(d){return !!d&&typeof d==='object'&&Number.isFinite(d.serverTime)&&Number.isFinite(d.deadline)&&d.deadline>1700000000000&&d.deadline<2200000000000&&typeof d.eventDate==='string'&&/^20\d\d-\d\d-\d\d$/.test(d.eventDate)&&Number.isFinite(Date.parse(d.eventDate+'T12:00:00Z'))&&Number.isInteger(d.capacity)&&d.capacity>=0&&d.capacity<=100&&Array.isArray(d.guests)&&d.guests.length<=100&&d.guests.every(g=>g&&typeof g.id==='string'&&g.id.length<=80&&typeof g.name==='string'&&g.name.length<=90&&['pending','confirmed','declined','wasted'].includes(g.status)&&['invite','reserve'].includes(g.role));}
function tick(){const deadline=state?.deadline||defaultDeadline;const sec=Math.max(0,Math.floor((deadline-now())/1000));const vals=[Math.floor(sec/86400),Math.floor(sec/3600)%24,Math.floor(sec/60)%60,sec%60];['days','hours','minutes','seconds'].forEach((id,i)=>$(id).textContent=String(vals[i]).padStart(2,'0'));const expired=now()>=deadline;document.body.classList.toggle('expired',expired);$('armed').textContent=expired?'TIDEN ER UTE':'INVITASJONEN ER ARMERT';$('deadline-title').textContent=expired?'WASTED.':'IKKE MIST PLASSEN.';$('timer').setAttribute('aria-label',expired?'Svarfristen har gått ut':`${vals[0]} dager, ${vals[1]} timer og ${vals[2]} minutter igjen`);if(expired!==lastExpired){lastExpired=expired;render();}}
function card(g,i){const ready=g.status==='confirmed',wasted=g.status==='wasted'||(g.role==='invite'&&g.status==='pending'&&now()>=state.deadline),photo=ready?imageURL(g.photo):'',initials=g.name.split(/\s+/).slice(0,2).map(v=>v[0]).join('');let body='';if(ready){body=`<span class="nickname">${escape(g.nickname)}</span><h4>DERFOR ELSKER JEG GTA 6</h4><p>${escape(g.gta)}</p><h4>DERFOR ER JEG HYTTEKLAR</h4><p>${escape(g.cabin)}</p><blockquote>«${escape(g.quote)}»</blockquote><small class="fiction">Vennskapelig, oppdiktet gaminghumor.</small>`;}else{body=`<div class="redacted" aria-hidden="true"><span></span><span></span><span></span></div><p class="locked-note">${wasted?'For sent. En reserve kan overta plassen.':g.status==='declined'?'Denne spilleren står over turen.':'Profilen avsløres når du bekrefter.'}</p>${g.status==='pending'&&!wasted?`<button class="card-button" data-join="${escape(g.id)}">${g.role==='reserve'?'Reserveplass':'Dette er meg'} <span>↗</span></button>`:''}`;}const status=ready?'✓ BEINKLAR FOR LAN':wasted?'WASTED':g.status==='declined'?'STÅR OVER':g.role==='reserve'?'RESERVE':'IKKE BEKREFTET';return `<article class="card ${ready?'ready':wasted?'wasted':''}" id="guest-${escape(g.id)}"><div class="portrait ${ready?'':'locked'}"><span class="initials" aria-hidden="true">${ready?escape(initials):'?'}</span>${photo?`<img src="${escape(photo)}" alt="Bilde av ${escape(g.name)}" loading="lazy" referrerpolicy="no-referrer">`:''}<span class="file">PLAYER / ${String(i+1).padStart(2,'0')}</span><div class="badge">${status}</div></div><div class="card-body"><h3>${escape(g.name)}</h3>${body}</div></article>`;}
function render(){if(!state)return;$('confirmed').textContent=String(state.guests.filter(g=>g.status==='confirmed').length).padStart(2,'0');$('capacity').textContent='/'+String(state.capacity).padStart(2,'0');$('deadline-text').textContent=formatDeadline(state.deadline);document.querySelectorAll('[data-date]').forEach(e=>e.textContent=formatDate(state.eventDate));const list=state.guests.filter(g=>filter==='all'||(filter==='ready'?g.status==='confirmed':g.status!=='confirmed'));$('crew-grid').innerHTML=state.guests.length===0?'<div class="empty"><div class="empty-icon">?</div><h3>NAVNELISTEN ER IKKE LAGT INN ENNÅ.</h3><p>Verten må legge inn deltakerne før du kan velge navnet ditt. Ingen er forhåndspåmeldt.</p><button class="empty-button" data-join>Åpne påmeldingen ↗</button></div>':list.length===0?'<div class="empty"><h3>INGEN SPILLERE HER ENNÅ.</h3><p>Prøv et annet filter.</p></div>':list.map(g=>card(g,state.guests.indexOf(g))).join('');document.querySelectorAll('.portrait img').forEach(im=>im.addEventListener('error',()=>im.remove(),{once:true}));$('sync-status').textContent='Felles svar hentet '+new Intl.DateTimeFormat('nb-NO',{timeZone:'Europe/Oslo',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(state.serverTime))+'. Åpne påmeldingen igjen for å hente nyere svar.';}
function openRegistration(guest=''){nonce=crypto.randomUUID();const url=new URL('/lan-share.html',BACKEND);url.searchParams.set('from',location.origin);url.searchParams.set('nonce',nonce);if(guest)url.searchParams.set('guest',guest);popup=window.open(url.href,'hyttelan-registration','popup,width=570,height=780');$('popup-fallback').hidden=!!popup;$('fallback-link').href=url.href;if(popup){popup.focus();$('sync-status').textContent='Påmeldingen er åpnet i eget vindu. Når listen er hentet der, vises den også her.';}else $('popup-fallback').scrollIntoView({block:'center',behavior:'smooth'});}
window.addEventListener('message',event=>{if(event.origin!==BACKEND||event.source!==popup||!event.data||event.data.type!=='hyttelan-state'||event.data.nonce!==nonce||!validState(event.data.state))return;const incoming=event.data.state;if(state&&incoming.serverTime<state.serverTime)return;const previous=new Set((state?.guests||[]).filter(g=>g.status==='confirmed').map(g=>g.id));state={serverTime:incoming.serverTime,deadline:incoming.deadline,eventDate:incoming.eventDate,capacity:incoming.capacity,guests:incoming.guests.map(g=>({id:g.id,name:g.name,status:g.status,role:g.role,nickname:String(g.nickname||'').slice(0,100),gta:String(g.gta||'').slice(0,1500),cabin:String(g.cabin||'').slice(0,1500),quote:String(g.quote||'').slice(0,400),photo:imageURL(g.photo)}))};clockBase=state.serverTime;perfBase=performance.now();render();tick();const unlocked=state.guests.find(g=>g.status==='confirmed'&&!previous.has(g.id));if(unlocked)toast('MISSION PASSED · '+unlocked.name+' er beinklar!');});
document.addEventListener('click',event=>{const target=event.target instanceof Element?event.target:null;if(!target)return;const join=target.closest('[data-join]');if(join){openRegistration(join.getAttribute('data-join')||'');return;}const f=target.closest('[data-filter]');if(f){filter=f.getAttribute('data-filter');document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===f)));render();return;}if(target.closest('[data-share]'))void share();});
$('sync').addEventListener('click',()=>openRegistration());
async function share(){const url=new URL('./',location.href).href;try{if(navigator.share)await navigator.share({title:'Hyttelan VI · Hovden',text:'19. november. Samme gjeng. Nytt kaos. Er du med?',url});else{await navigator.clipboard.writeText(url);toast('Invitasjonslenken er kopiert.');}}catch(e){if(e.name!=='AbortError')toast('Del denne adressen: '+url);}}
$('calendar').addEventListener('click',()=>{const start=state?.eventDate||'2026-11-19';const end=new Date(start+'T12:00:00Z');end.setUTCDate(end.getUTCDate()+1);const content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Hyttelan//Hovden//NO','BEGIN:VEVENT','UID:hyttelan-hovden-2026@inmoment.no','DTSTAMP:'+new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,''),'DTSTART;VALUE=DATE:'+start.replaceAll('-',''),'DTEND;VALUE=DATE:'+end.toISOString().slice(0,10).replaceAll('-',''),'SUMMARY:Hyttelan VI på Hovden','LOCATION:Hovden','DESCRIPTION:Ankomst og praktiske detaljer avtales med verten.','END:VEVENT','END:VCALENDAR'].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'text/calendar;charset=utf-8'}));a.download='Hyttelan-Hovden.ics';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);});
tick();setInterval(tick,1000);
})();
