/* Hyttelan: server-confirmed attendance; profile visibility is independent.
   The browser contains only a public anon key. No service keys or admin rights.
   Request IDs are retry references, not identity verification or a database. */
(()=>{'use strict';
const C=window.HYTTELAN_CONFIG,$=id=>document.getElementById(id),dialog=$('rsvp-dialog');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=C.bootstrap,synced=false,loading=false,sending=false,filter='all',query='',clockBase=Date.now(),perfBase=performance.now(),lastSig='',toastTimer=null,afterClose='';
const requests=new Map(),now=()=>clockBase+performance.now()-perfBase;
const fmtDate=s=>new Intl.DateTimeFormat('nb-NO',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Oslo'}).format(new Date(s+'T12:00:00Z'));
const fmtDeadline=t=>new Intl.DateTimeFormat('nb-NO',{weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Oslo'}).format(new Date(t));
const visible=g=>state.profileVisibility==='open'||g.status==='confirmed'||g.profileVisible===true;
function imageUrl(s){try{const u=new URL(s);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}}
function valid(s){return s&&s.ok!==false&&Number.isFinite(s.serverTime)&&Number.isFinite(s.deadline)&&Number.isInteger(s.capacity)&&s.capacity>=1&&s.capacity<=100&&typeof s.registrationOpen==='boolean'&&['open','on_confirmation'].includes(s.profileVisibility)&&/^20\d{2}-\d{2}-\d{2}$/.test(s.eventDate||'')&&Array.isArray(s.guests)&&s.guests.length<=100&&s.guests.every(g=>g&&typeof g.id==='string'&&typeof g.name==='string'&&g.name.length<=90&&['invite','reserve'].includes(g.role)&&['pending','confirmed','declined','wasted'].includes(g.status));}
function toast(s){clearTimeout(toastTimer);$('toast').textContent=s;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,6500);}
function fixIcons(){if(location.hostname==='htmlpreview.github.io')document.querySelectorAll('svg use').forEach(e=>{const h=e.getAttribute('href');if(h?.startsWith('#'))e.setAttribute('href',location.href.split('#')[0]+h);});}
class ApiError extends Error{constructor(message,code){super(message);this.code=code;}}
async function rpc(name,body){
 const ctrl=new AbortController(),timeout=setTimeout(()=>ctrl.abort(),18000);
 const headers={'Content-Type':'application/json','Accept':'application/json','apikey':C.backend.publishableKey};
 if(C.backend.publishableKey.startsWith('eyJ'))headers.Authorization='Bearer '+C.backend.publishableKey;
 try{const r=await fetch(C.backend.url+'/rest/v1/rpc/'+name,{method:'POST',headers,body:JSON.stringify(body),signal:ctrl.signal,credentials:'omit',cache:'no-store'});const d=await r.json().catch(()=>null);
 if(!r.ok)throw new ApiError('Kunne ikke kontakte påmeldingen. Ingen ny bekreftelse er gitt. Prøv igjen.','http_'+r.status);
 if(!d||d.ok===false)throw new ApiError(d?.message||'Serveren ga ikke et gyldig svar.',d?.code||'invalid_response');return d;
 }catch(e){if(e instanceof ApiError)throw e;if(e.name==='AbortError')throw new ApiError('Svaret tok for lang tid. Prøv igjen med samme navn; samme forsøk registreres ikke dobbelt.','timeout');throw new ApiError('Nettverksfeil. Prøv igjen når forbindelsen er tilbake.','network');}finally{clearTimeout(timeout);}
}
function card(g,i){const open=visible(g),ready=g.status==='confirmed',expired=g.status==='wasted',photo=open?imageUrl(g.photo):'';
 const initials=g.name.split(/\s+/).slice(0,2).map(x=>x[0]).join('');
 const status=!synced?'HENTER SVARSTATUS':ready?'✓ BEINKLAR FOR LAN':expired?'WASTED':g.status==='declined'?'STÅR OVER':g.role==='reserve'?'RESERVE':'IKKE SVART ENNÅ';
 const bio=open?'<span class="nickname">'+esc(g.nickname)+'</span><h4>DERFOR ELSKER JEG GTA 6</h4><p>'+esc(g.gta)+'</p><h4>DERFOR ER JEG HYTTEKLAR</h4><p>'+esc(g.cabin)+'</p><blockquote>«'+esc(g.quote)+'»</blockquote><small class="fiction">GTA-inspirert illustrasjon. Fiktiv LAN-rolle og vennskapelig gaminghumor.</small>':'<div class="redacted" aria-hidden="true"><span></span><span></span><span></span><span></span></div><p class="locked-note">Profilen åpnes når du bekrefter.</p>';
 const canRespond=g.status==='pending'&&state.registrationOpen&&(g.role==='reserve'?now()>=state.deadline:now()<state.deadline);
 return '<article class="card '+(ready?'ready':open?'profile-open':expired?'wasted':'locked')+'" id="guest-'+esc(g.id)+'"><div class="portrait '+(open?'':'locked')+'"><span class="initials" aria-hidden="true">'+(open?esc(initials):'?')+'</span>'+(photo?'<img src="'+esc(photo)+'" alt="GTA-inspirert illustrasjon merket '+esc(g.name)+'" width="255" height="205" loading="lazy" referrerpolicy="no-referrer">':'')+'<span class="file">PLAYER / '+String(i+1).padStart(2,'0')+'</span><div class="badge">'+status+'</div></div><div class="card-body"><h3>'+esc(g.name)+'</h3>'+bio+(canRespond?'<button class="card-button" data-join="'+esc(g.id)+'">Dette er meg <span>↗</span></button>':'')+'</div></article>';
}
function render(){const sig=JSON.stringify([state.guests,state.profileVisibility,state.registrationOpen,state.deadline,filter,query,synced]);if(sig===lastSig)return;lastSig=sig;
 const total=state.guests.length,ready=state.guests.filter(g=>g.status==='confirmed').length;
 $('confirmed').textContent=synced?String(ready):'··';$('capacity').textContent=String(state.capacity);
 const list=state.guests.filter(g=>(filter==='all'||(filter==='ready'?g.status==='confirmed':g.status!=='confirmed'))&&(g.name+' '+(g.nickname||'')).toLocaleLowerCase('nb-NO').includes(query));
 $('crew-grid').innerHTML=list.length?list.map(g=>card(g,state.guests.indexOf(g))).join(''):'<div class="empty-state"><h3>INGEN TREFF AKKURAT HER.</h3><p>Velg «Alle» eller søk etter et annet navn.</p></div>';
 $('crew-grid').setAttribute('aria-busy','false');$('profile-count').textContent=list.length+' / '+total+' PROFILER';
 document.querySelector('.crew-header p').textContent=state.profileVisibility==='open'?total+' personer. Alle profiler er åpne. BEINKLAR betyr bekreftet påmelding.':'Velg navnet ditt og bekreft for å åpne din spillermappe.';
 $('profile-mode').textContent=state.profileVisibility==='open'?'ALLE PROFILER ER ÅPNE · STATUS OPPDATERES NÅR HVER PERSON SVARER':'PROFILENE ÅPNES VED BEKREFTELSE';
 $('deadline-text').textContent='SVARFRIST: '+fmtDeadline(state.deadline).toUpperCase();
 document.querySelectorAll('[data-date]').forEach(e=>e.textContent=fmtDate(state.eventDate));
 $('trust-note').textContent='Velg bare ditt eget navn. Påmeldingen er tillitsbasert, uten innlogging. En åpen profil betyr ikke at personen har bekreftet. Kontakt verten ved feil.';
 document.querySelectorAll('.portrait img').forEach(img=>img.addEventListener('error',()=>img.remove(),{once:true}));fixIcons();
}
function accept(s){if(!valid(s))throw new ApiError('Ugyldig serverrespons. Ingen ny status er bekreftet.','invalid_state');if(synced&&s.serverTime<state.serverTime)return;state=s;synced=true;clockBase=s.serverTime;perfBase=performance.now();render();tick();$('sync').classList.remove('failed');$('sync-label').textContent='LIVE CREW';$('sync-status').classList.remove('error');$('sync-status').textContent='Felles svar oppdatert '+new Intl.DateTimeFormat('nb-NO',{hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:'Europe/Oslo'}).format(new Date(s.serverTime))+'. Oppdateres automatisk.';}
async function refresh(){if(loading)return;loading=true;try{accept(await rpc('hyttelan_state',{p_event_id:C.eventId}));}catch(e){synced=false;$('sync').classList.add('failed');$('sync-label').textContent='PRØV IGJEN';$('sync-status').classList.add('error');$('sync-status').textContent=e.message+' Profilene vises fortsatt. Eksisterende status kan være utdatert.';render();}finally{loading=false;}}
let wasExpired=false;
function tick(){const sec=Math.max(0,Math.floor((state.deadline-now())/1000)),v=[Math.floor(sec/86400),Math.floor(sec/3600)%24,Math.floor(sec/60)%60,sec%60];['days','hours','minutes','seconds'].forEach((id,i)=>$(id).textContent=String(v[i]).padStart(2,'0'));const expired=now()>=state.deadline&&state.registrationOpen;document.body.classList.toggle('expired',expired);$('expired-title').hidden=!expired;$('timer').setAttribute('aria-label',expired?'Svarfristen har gått ut':v[0]+' dager, '+v[1]+' timer og '+v[2]+' minutter igjen');$('fuse-progress').style.width=Math.max(0,Math.min(100,(state.deadline-now())/86400000*100))+'%';$('deadline-warning').innerHTML=state.registrationOpen?'Svar før fristen. Ellers blir du <b>WASTED</b>, og en reserve kan ta plassen din.':'Påmeldingen er satt på pause av verten. Profilene forblir synlige.';if(expired!==wasExpired){wasExpired=expired;lastSig='';render();void refresh();}}
function selectList(preferred){const select=$('rsvp-name');const options=[new Option('Velg ditt eget navn','')];for(const g of state.guests){const suffix=g.status==='confirmed'?' · allerede beinklar':g.status==='declined'?' · står over':g.status==='wasted'?' · fristen utløpt':g.role==='reserve'?' · reserve':'';const o=new Option(g.name+suffix,g.id);o.disabled=g.status!=='pending'||(g.role==='reserve'&&now()<state.deadline)||(g.role==='invite'&&now()>=state.deadline);options.push(o);}select.replaceChildren(...options);select.value=options.some(o=>o.value===preferred&&!o.disabled)?preferred:'';}
function preview(){const g=state.guests.find(g=>g.id===$('rsvp-name').value);$('rsvp-person').textContent=g?g.name:'Spillermappen din';$('rsvp-hint').textContent=g?(visible(g)?g.nickname:'Profilen avsløres etter bekreftelsen.'):'Navnet knytter bekreftelsen til riktig spiller.';$('rsvp-submit').disabled=sending||!g||!synced;}
function openJoin(id=''){afterClose='';$('rsvp-title').textContent='ER DU MED?';$('rsvp-title').classList.remove('success-title');$('rsvp-intro').textContent='Velg ditt eget navn. Du er først påmeldt når svaret er lagret.';$('rsvp-form').hidden=false;$('rsvp-result').hidden=true;$('rsvp-error').hidden=true;$('rsvp-consent').checked=false;$('rsvp-name').disabled=false;$('rsvp-decline').disabled=false;$('rsvp-submit').textContent='Jeg er beinklar!';selectList(id);preview();$('rsvp-footnote').textContent='Svarfrist: '+fmtDeadline(state.deadline)+'. Norsk tid.';
 if(!synced||!state.registrationOpen){$('rsvp-form').hidden=true;$('rsvp-result').hidden=false;$('rsvp-result-text').textContent=!synced?'Vi får ikke kontakt med serveren. Lukk vinduet og trykk «Prøv igjen». Ingen ny påmelding er bekreftet.':'Verten har satt påmeldingen på pause.';$('rsvp-title').textContent='PÅMELDINGEN VENTER.';}
 else if(!state.guests.some(g=>g.status==='pending'&&(g.role==='reserve'?now()>=state.deadline:now()<state.deadline))){$('rsvp-form').hidden=true;$('rsvp-result').hidden=false;$('rsvp-result-text').textContent=now()>=state.deadline?'Svarfristen er ute. Verten kan gi en reserve en ledig plass.':'Alle inviterte har svart. Kontakt verten dersom navnet ditt mangler.';$('rsvp-title').textContent=now()>=state.deadline?'WASTED.':'ALLE HAR SVART.';}
 if(!dialog.open)dialog.showModal();}
function closeJoin(){if(sending)return;dialog.close();if(afterClose){const id=afterClose;afterClose='';setTimeout(()=>document.getElementById('guest-'+id)?.scrollIntoView({behavior:'smooth',block:'center'}),30);}}
function requestId(id,choice){const k=C.eventId+':'+id+':'+choice;if(requests.has(k))return requests.get(k);let value;try{value=sessionStorage.getItem('lan-request:'+k);}catch{}if(!/^[a-f0-9-]{36}$/.test(value||''))value=crypto.randomUUID();requests.set(k,value);try{sessionStorage.setItem('lan-request:'+k,value);}catch{}return value;}
async function respond(choice){if(sending||!$('rsvp-form').reportValidity())return;if(!synced){$('rsvp-error').textContent='Forbindelsen må gjenopprettes først.';$('rsvp-error').hidden=false;return;}const id=$('rsvp-name').value;if(!id)return;sending=true;$('rsvp-submit').disabled=$('rsvp-decline').disabled=$('rsvp-name').disabled=true;$('rsvp-submit').textContent='Lagrer…';$('rsvp-error').hidden=true;
 try{const r=await rpc('hyttelan_respond',{p_event_id:C.eventId,p_guest_id:id,p_choice:choice,p_request_id:requestId(id,choice),p_consent:$('rsvp-consent').checked});if(!valid(r.state))throw new ApiError('Bekreftelsen er ufullstendig. Prøv samme navn igjen.','invalid_result');const person=r.state.guests.find(g=>g.id===id);if(!person||person.status!==choice)throw new ApiError('Svaret kunne ikke bekreftes. Kontakt verten.','not_confirmed');accept(r.state);$('rsvp-form').hidden=true;$('rsvp-result').hidden=false;$('rsvp-title').textContent=choice==='confirmed'?'MISSION PASSED.':'SVAR REGISTRERT.';$('rsvp-title').classList.toggle('success-title',choice==='confirmed');$('rsvp-intro').textContent=choice==='confirmed'?person.name+' er BEINKLAR FOR LAN!':person.name+' står over turen.';$('rsvp-result-text').textContent='Svaret er lagret i den felles deltakerlisten og vises også for de andre. Ingen ekstra konto er nødvendig.';afterClose=id;
 }catch(e){$('rsvp-error').textContent=e.message;$('rsvp-error').hidden=false;if(['expired','full','already_answered','closed'].includes(e.code))void refresh();}
 finally{sending=false;$('rsvp-submit').disabled=$('rsvp-decline').disabled=$('rsvp-name').disabled=false;$('rsvp-submit').textContent='Jeg er beinklar!';}}
async function share(){const url=C.shareUrl||"https://raw.githack.com/oleemil/oleemil.github.io/main/hyttelan/index.html";try{if(navigator.share)await navigator.share({title:'HYTTELAN VI · Hovden',text:'19. november. Same crew. New story. Er du beinklar?',url});else{await navigator.clipboard.writeText(url);toast('Invitasjonslenken er kopiert.');}}catch(e){if(e.name!=='AbortError')toast('Del adressen fra nettleserens adressefelt.');}}
document.addEventListener('click',e=>{const t=e.target instanceof Element?e.target:null;if(!t)return;const j=t.closest('[data-join]');if(j){openJoin(j.getAttribute('data-join')||'');return;}const f=t.closest('[data-filter]');if(f){filter=f.getAttribute('data-filter');document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===f)));render();return;}if(t.closest('[data-share]'))void share();const a=t.closest('a');if(a?.hash&&a.hostname===location.hostname){const el=document.getElementById(a.hash.slice(1));if(el){e.preventDefault();el.scrollIntoView({behavior:'smooth'});}}});
$('profile-search').addEventListener('input',e=>{query=e.target.value.trim().toLocaleLowerCase('nb-NO');render();});$('rsvp-name').addEventListener('change',preview);$('rsvp-form').addEventListener('submit',e=>{e.preventDefault();void respond('confirmed');});$('rsvp-decline').addEventListener('click',()=>void respond('declined'));dialog.querySelector('.modal-close').addEventListener('click',closeJoin);$('rsvp-done').addEventListener('click',closeJoin);dialog.addEventListener('cancel',e=>{if(sending)e.preventDefault();});$('sync').addEventListener('click',()=>void refresh());
$('calendar').addEventListener('click',()=>{const d=state.eventDate,end=new Date(d+'T12:00:00Z');end.setUTCDate(end.getUTCDate()+1);const text=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Hyttelan//Hovden//NO','BEGIN:VEVENT','UID:hyttelan-'+C.eventId+'@oleemil.github.io','DTSTAMP:'+new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,''),'DTSTART;VALUE=DATE:'+d.replaceAll('-',''),'DTEND;VALUE=DATE:'+end.toISOString().slice(0,10).replaceAll('-',''),'SUMMARY:Hyttelan VI på Hovden','LOCATION:Hovden','DESCRIPTION:Samkjøring og ankomst avtales med verten.','END:VEVENT','END:VCALENDAR'].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/calendar;charset=utf-8'}));a.download='Hyttelan-Hovden.ics';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);});
$('preview-note').hidden=location.hostname!=='htmlpreview.github.io';render();tick();void refresh();setInterval(tick,1000);setInterval(()=>{if(!document.hidden)void refresh();},7000);window.addEventListener('focus',()=>void refresh());document.addEventListener('visibilitychange',()=>{if(!document.hidden)void refresh();});
})();
